apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: andy-os
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: andy-os
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "andy-os-frontend"
          imagePullPolicy: Never
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]